[package]
name = "optimism"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.18", default-features = false, features = ["multi_threaded"] }
micromegas = "0.20"

[dev-dependencies]
serial_test = "3.2"
